### PR TITLE
Add dark theme, according to system preferences

### PR DESCRIPTION
**Pull request by kevinjuanjacque**
Demo

image

### CODE REVIEW

**Comment by baumannzone** [comment]
#### 📝 Changed routes:


| [**/blog/_slug**](https://baumannzone-id5ug12ac-baumannzone.vercel.app/blog/_slug) | [**/uses**](https://baumannzone-id5ug12ac-baumannzone.vercel.app/uses) |
|:-:|:-:|
|<a href="https://baumannzone-id5ug12ac-baumannzone.vercel.app/blog/_slug">Screenshot of /blog/_slug</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/yzPSJaLdFxtvROLCE07i_l-n5Om4mFxXbfOlMbXhCbQWZ6zpYavd15QAok80vSwFDSNaQLBrpiF5Lxnysi6OEA.png">(view full size)</a> |<a href="https://baumannzone-id5ug12ac-baumannzone.vercel.app/uses">Screenshot of /uses</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/6PnpSvBdSfAK9HO669GItez9EZoDO-sNAHiyoPU9Ifh_4hbpSYxuOypT5UrMIp8v7ZjNgcv_oxNjYKz6Bxil6Q.png">(view full size)</a> |







Commit d758b52ab90b77472117d028e6c67d4d039637d0 (https://baumannzone-id5ug12ac-baumannzone.vercel.app).

**Comment by baumannzone** [comment]
Está brutal, lo aceptaré, pero puedes antes revisar esta pag y fijarte en esto?

https://baumannzone-id5ug12ac-baumannzone.vercel.app/blog/testing-con-javascript

image

**Comment by kevinjuanjacque** [comment]
@baumannzone ouuu... realizo el fix altiro, te aviso

**Comment by kevinjuanjacque** [comment]
@baumannzone fixed 🎉

**Comment by kevinjuanjacque** [comment]
@baumannzone wait, me falto el error not found estoy en eso

**Comment by kevinjuanjacque** [comment]
@baumannzone creo que ahora esta fixed todo, igual me avisas si encuentras algo ❤️

**Pull request merged**
